package evenFibonacciNumbers;

public class Main {

	/*	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

		By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/
	
	public static void main(String[] args) {
		int fibonacciCeiling = 4000000;
		
		int firstValue = 1;
		int secondValue = 2;
		
		int totalSum = 0;
		
		while(firstValue <= fibonacciCeiling && secondValue <= fibonacciCeiling){
			if(secondValue % 2 == 0){
				totalSum += secondValue;
			}
			
			int tempValue = firstValue;
			firstValue = secondValue;
			secondValue = firstValue + tempValue;
			
			System.out.print(tempValue + " ");
		}
		
		System.out.println();
		
		System.out.println(totalSum);

	}

}
